# Generated by Django 2.1.5 on 2022-02-02 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220202_1950'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='summary',
            field=models.BooleanField(),
        ),
    ]
